import {
  BudgetComfort,
  DurationPreference,
  ExperienceLevel,
  FormatPreference,
  GpaRange,
  GradeLevel,
  LocationComfort,
  ResidentialPreference,
  SelectivityComfort,
  StudentProfile,
} from "@/types";

export const initialProfile: StudentProfile = {
  gradeLevel: "11",
  gpaRange: "3.6-3.8",
  dreamMajor: "",
  academicInterests: [],
  summerGoals: [],
  courseworkBackground: [],
  extracurriculars: [],
  achievements: [],
  academicStrengths: [],
  priorExperienceLevel: "some experience",
  budgetComfort: "moderate",
  formatPreference: "either",
  locationComfort: "same region",
  homeState: "",
  residentialPreference: "either",
  durationPreference: "3-4 weeks",
  selectivityComfort: "balanced",
  programExcitement: "",
  avoidNotes: "",
};

export const sampleProfiles: Array<{ id: string; label: string; description: string; profile: StudentProfile }> = [
  {
    id: "ai-cs",
    label: "AI / CS Student",
    description: "Strong CS interest, wants project depth and a more serious summer.",
    profile: {
      gradeLevel: "11",
      gpaRange: "3.6-3.8",
      dreamMajor: "Computer Science",
      academicInterests: ["AI", "machine learning", "software engineering"],
      summerGoals: ["research exposure", "hands-on projects", "portfolio building"],
      courseworkBackground: ["AP Computer Science A", "AP Calculus AB", "AP Statistics"],
      extracurriculars: ["Coding Club", "Math Team", "peer tutoring"],
      achievements: ["built a study app", "regional hackathon finalist"],
      academicStrengths: ["coding", "math", "self-directed learning"],
      priorExperienceLevel: "some experience",
      budgetComfort: "moderate",
      formatPreference: "either",
      locationComfort: "same region",
      homeState: "Arizona",
      residentialPreference: "either",
      durationPreference: "5-6 weeks",
      selectivityComfort: "highly selective is fine",
      programExcitement: "A serious AI or product-building program with real output sounds exciting.",
      avoidNotes: "Not looking for a lecture-only program.",
    },
  },
  {
    id: "pre-med",
    label: "Pre-Med Student",
    description: "Science-first profile, wants health exposure without spending too much.",
    profile: {
      gradeLevel: "11",
      gpaRange: "3.9+",
      dreamMajor: "Biology",
      academicInterests: ["medicine", "public health", "neuroscience"],
      summerGoals: ["career exploration", "research exposure", "academic challenge"],
      courseworkBackground: ["AP Biology", "AP Chemistry", "Honors Anatomy"],
      extracurriculars: ["HOSA", "hospital volunteering", "Science Olympiad"],
      achievements: ["regional HOSA medalist", "organized a school blood drive"],
      academicStrengths: ["science coursework", "service", "consistency"],
      priorExperienceLevel: "some experience",
      budgetComfort: "low",
      formatPreference: "either",
      locationComfort: "anywhere in US",
      homeState: "Georgia",
      residentialPreference: "either",
      durationPreference: "3-4 weeks",
      selectivityComfort: "balanced",
      programExcitement: "A health or research program with real cases or community impact sounds exciting.",
      avoidNotes: "Would rather skip something that is too expensive without aid.",
    },
  },
  {
    id: "business",
    label: "Business Student",
    description: "Leadership-heavy student looking for practical business experience.",
    profile: {
      gradeLevel: "11",
      gpaRange: "3.3-3.5",
      dreamMajor: "Business",
      academicInterests: ["entrepreneurship", "marketing", "economics"],
      summerGoals: ["career exploration", "leadership", "hands-on projects"],
      courseworkBackground: ["AP Macroeconomics", "AP Statistics", "Honors Precalculus"],
      extracurriculars: ["DECA", "Student Government", "yearbook"],
      achievements: ["DECA district finalist", "ran a student merch sale"],
      academicStrengths: ["communication", "initiative", "team leadership"],
      priorExperienceLevel: "some experience",
      budgetComfort: "low",
      formatPreference: "either",
      locationComfort: "same region",
      homeState: "Texas",
      residentialPreference: "non-residential preferred",
      durationPreference: "3-4 weeks",
      selectivityComfort: "prefer realistic options",
      programExcitement: "A startup, product, or campaign-style program would be a good fit.",
      avoidNotes: "Not interested in something that feels too academic or abstract.",
    },
  },
  {
    id: "humanities",
    label: "Humanities Student",
    description: "Writing-heavy student who wants a stronger public-facing summer.",
    profile: {
      gradeLevel: "10",
      gpaRange: "3.6-3.8",
      dreamMajor: "Public Policy",
      academicInterests: ["writing", "history", "government"],
      summerGoals: ["leadership", "research exposure", "academic challenge"],
      courseworkBackground: ["AP World History", "AP English Language", "Honors Government"],
      extracurriculars: ["Debate", "school newspaper", "community volunteering"],
      achievements: ["state speech finalist", "published an op-ed in a local paper"],
      academicStrengths: ["writing", "public speaking", "close reading"],
      priorExperienceLevel: "some experience",
      budgetComfort: "moderate",
      formatPreference: "in-person only",
      locationComfort: "same region",
      homeState: "Virginia",
      residentialPreference: "either",
      durationPreference: "3-4 weeks",
      selectivityComfort: "balanced",
      programExcitement: "A seminar-driven program with writing, policy, or debate would be exciting.",
      avoidNotes: "Would rather skip generic leadership camps.",
    },
  },
];

export const sampleProfile = sampleProfiles[0].profile;

export const formOptions: {
  gradeLevels: GradeLevel[];
  gpaRanges: GpaRange[];
  budgetComfort: BudgetComfort[];
  formatPreference: FormatPreference[];
  locationComfort: LocationComfort[];
  residentialPreference: ResidentialPreference[];
  durationPreference: DurationPreference[];
  selectivityComfort: SelectivityComfort[];
  priorExperienceLevel: ExperienceLevel[];
} = {
  gradeLevels: ["9", "10", "11", "12"],
  gpaRanges: ["3.9+", "3.6-3.8", "3.3-3.5", "3.0-3.2", "below 3.0"],
  budgetComfort: ["low", "moderate", "high", "not a major concern"],
  formatPreference: ["in-person only", "online only", "either"],
  locationComfort: ["local / same state", "same region", "anywhere in US", "international okay"],
  residentialPreference: ["residential preferred", "non-residential preferred", "either"],
  durationPreference: ["1-2 weeks", "3-4 weeks", "5-6 weeks", "flexible"],
  selectivityComfort: ["highly selective is fine", "balanced", "prefer realistic options"],
  priorExperienceLevel: ["beginner", "some experience", "advanced"],
};
