import { StudentProfile } from "@/types";

export const initialProfile: StudentProfile = {
  dreamMajor: "",
  dreamUniversities: [],
  dreamPrograms: [],
  academicInterests: [],
  careerInterests: [],
  gradeLevel: "11",
  gpaRange: "3.6-3.8",
  budgetLevel: "moderate",
  locationPreference: "no strong preference",
  summerAvailability: "4-6 weeks",
  selectivityComfort: "balanced",
  desiredStyles: [],
  coursesAvailable: [],
  clubsAvailable: [],
  leadershipOpportunities: [],
  localResearchAvailable: false,
  internshipsAvailable: false,
  volunteeringShadowingAvailable: false,
  counselingSupport: "moderate",
  extracurriculars: [],
  leadershipRoles: [],
  projectsAwardsCompetitions: [],
  strengths: [],
  weaknesses: [],
  testSituation: "no SAT/ACT yet",
  testingConfidence: "medium",
  personalStatementThemes: [],
  majorExperiences: [],
  essayWritingConfidence: "medium",
};

export const sampleProfile: StudentProfile = {
  dreamMajor: "Computer Science",
  dreamUniversities: ["Stanford", "Carnegie Mellon", "Georgia Tech", "Arizona State University"],
  dreamPrograms: ["Summit AI Research Lab", "Applied AI for Good"],
  academicInterests: ["AI", "machine learning", "software engineering"],
  careerInterests: ["AI engineer", "product builder"],
  gradeLevel: "11",
  gpaRange: "3.6-3.8",
  budgetLevel: "moderate",
  locationPreference: "west coast",
  summerAvailability: "4-6 weeks",
  selectivityComfort: "reach-heavy",
  desiredStyles: ["research", "internship-like", "on-campus residential"],
  coursesAvailable: ["AP Computer Science A", "AP Calculus AB", "AP Physics 1", "Dual Enrollment Statistics", "Honors English"],
  clubsAvailable: ["Robotics Club", "Coding Club", "Math Team", "Student Government", "NHS"],
  leadershipOpportunities: ["Robotics project lead", "Coding Club officer", "Hackathon organizer", "Peer tutoring"],
  localResearchAvailable: false,
  internshipsAvailable: false,
  volunteeringShadowingAvailable: true,
  counselingSupport: "moderate",
  extracurriculars: ["Coding Club", "Math Team", "peer tutoring"],
  leadershipRoles: ["Math Team captain"],
  projectsAwardsCompetitions: ["built a study app", "regional hackathon finalist", "AMC participant"],
  strengths: ["coding foundation", "math", "self-driven projects"],
  weaknesses: ["limited research experience", "wants stronger leadership depth", "essay story feels scattered"],
  testSituation: "no SAT/ACT yet",
  testingConfidence: "medium",
  personalStatementThemes: ["building tools for students", "curiosity about AI", "balancing ambition with self-doubt"],
  majorExperiences: ["self-taught programming", "helping classmates with math", "first family member aiming for elite STEM schools"],
  essayWritingConfidence: "medium",
};

export const sampleProfiles: Array<{ id: string; label: string; description: string; profile: StudentProfile }> = [
  {
    id: "cs-builder",
    label: "AI / CS Student",
    description: "Selective CS goals, strong math base, needs more research proof",
    profile: sampleProfile,
  },
  {
    id: "pre-med",
    label: "Pre-Med Student",
    description: "Strong science student with service and health goals",
    profile: {
      dreamMajor: "Biology",
      dreamUniversities: ["Johns Hopkins", "Emory", "Case Western", "University of Pittsburgh"],
      dreamPrograms: ["BioFuture Medical Scholars", "Community Health Research Collaborative"],
      academicInterests: ["biology", "public health", "neuroscience"],
      careerInterests: ["physician", "public health researcher"],
      gradeLevel: "11",
      gpaRange: "3.9+",
      budgetLevel: "moderate",
      locationPreference: "east coast",
      summerAvailability: "4-6 weeks",
      selectivityComfort: "balanced",
      desiredStyles: ["research", "academic enrichment", "on-campus residential"],
      coursesAvailable: ["AP Biology", "AP Chemistry", "AP Statistics", "Honors Anatomy", "Dual Enrollment Psychology"],
      clubsAvailable: ["HOSA", "Science Olympiad", "Key Club", "NHS", "Debate"],
      leadershipOpportunities: ["HOSA officer", "peer health club lead", "hospital volunteer coordinator"],
      localResearchAvailable: false,
      internshipsAvailable: false,
      volunteeringShadowingAvailable: true,
      counselingSupport: "strong",
      extracurriculars: ["HOSA", "hospital volunteering", "Science Olympiad"],
      leadershipRoles: ["Key Club secretary"],
      projectsAwardsCompetitions: ["regional HOSA medalist", "organized a school blood drive"],
      strengths: ["science coursework", "service orientation", "reliability"],
      weaknesses: ["limited lab research", "testing anxiety", "story feels too conventional"],
      testSituation: "SAT taken",
      testingConfidence: "low",
      personalStatementThemes: ["service in healthcare settings", "watching family navigate illness", "learning to stay calm under pressure"],
      majorExperiences: ["weekly hospital volunteering", "supporting an ill grandparent", "health education project at school"],
      essayWritingConfidence: "medium",
    },
  },
  {
    id: "policy-writer",
    label: "Policy / Humanities Student",
    description: "Writing-heavy student with public policy goals and a tighter budget",
    profile: {
      dreamMajor: "Public Policy",
      dreamUniversities: ["Georgetown", "George Washington", "William & Mary", "American University"],
      dreamPrograms: ["Civic Humanities Fellows", "Policy and Media Institute"],
      academicInterests: ["history", "government", "writing", "politics"],
      careerInterests: ["policy analyst", "law", "journalism"],
      gradeLevel: "10",
      gpaRange: "3.6-3.8",
      budgetLevel: "low",
      locationPreference: "east coast",
      summerAvailability: "2-4 weeks",
      selectivityComfort: "balanced",
      desiredStyles: ["leadership", "research", "academic enrichment"],
      coursesAvailable: ["AP World History", "AP English Language", "Honors Government", "Debate elective", "Dual Enrollment Sociology"],
      clubsAvailable: ["Debate", "Model UN", "Student Government", "School Newspaper", "NHS"],
      leadershipOpportunities: ["student newspaper editor", "Model UN chair", "class representative"],
      localResearchAvailable: false,
      internshipsAvailable: true,
      volunteeringShadowingAvailable: true,
      counselingSupport: "limited",
      extracurriculars: ["Debate", "school newspaper", "community volunteering"],
      leadershipRoles: ["debate captain"],
      projectsAwardsCompetitions: ["state speech finalist", "published op-ed in a local paper"],
      strengths: ["writing voice", "public speaking", "initiative"],
      weaknesses: ["less quantitative rigor", "needs a stronger central theme", "limited counselor support"],
      testSituation: "not planning yet",
      testingConfidence: "medium",
      personalStatementThemes: ["finding a public voice", "speaking up for others", "navigating identity in community spaces"],
      majorExperiences: ["student newspaper investigations", "debate leadership", "city youth council participation"],
      essayWritingConfidence: "high",
    },
  },
  {
    id: "business-leader",
    label: "Business / Leadership Student",
    description: "Student leader with strong ownership, but needs more academic signal",
    profile: {
      dreamMajor: "Business",
      dreamUniversities: ["Babson", "Indiana University Bloomington", "Northeastern", "University of Texas at Austin"],
      dreamPrograms: ["Market Lab Leadership Fellows", "Venture Leaders Bootcamp"],
      academicInterests: ["business", "economics", "marketing"],
      careerInterests: ["founder", "brand strategist", "product manager"],
      gradeLevel: "11",
      gpaRange: "3.3-3.5",
      budgetLevel: "low",
      locationPreference: "south",
      summerAvailability: "4-6 weeks",
      selectivityComfort: "accessible",
      desiredStyles: ["leadership", "internship-like", "online"],
      coursesAvailable: ["AP English Language", "AP Macroeconomics", "AP Statistics", "Honors Precalculus", "Yearbook leadership"],
      clubsAvailable: ["DECA", "Student Government", "Yearbook", "Key Club", "NHS"],
      leadershipOpportunities: ["DECA chapter officer", "student government committee chair", "yearbook editor"],
      localResearchAvailable: false,
      internshipsAvailable: true,
      volunteeringShadowingAvailable: true,
      counselingSupport: "moderate",
      extracurriculars: ["DECA", "Student Government", "yearbook"],
      leadershipRoles: ["student government treasurer", "yearbook section editor"],
      projectsAwardsCompetitions: ["launched a student merch sale", "DECA district finalist", "organized a school fundraiser"],
      strengths: ["leadership", "initiative", "communication"],
      weaknesses: ["needs stronger academic rigor", "limited quantitative confidence", "summer plan feels generic"],
      testSituation: "no SAT/ACT yet",
      testingConfidence: "medium",
      personalStatementThemes: ["seeing gaps and acting on them", "learning to lead peers", "balancing school with part-time work"],
      majorExperiences: ["running school fundraising projects", "helping with a family business", "leading peer events"],
      essayWritingConfidence: "medium",
    },
  },
];

export const formOptions = {
  gradeLevels: ["9", "10", "11", "12"],
  gpaRanges: ["3.9+", "3.6-3.8", "3.3-3.5", "3.0-3.2", "below 3.0"],
  budgetLevels: ["low", "moderate", "high", "flexible"],
  locationPreferences: ["west coast", "east coast", "south", "midwest", "online only", "no strong preference"],
  summerAvailability: ["2-4 weeks", "4-6 weeks", "6-8 weeks", "flexible"],
  selectivityComfort: ["reach-heavy", "balanced", "accessible"],
  styles: ["research", "academic enrichment", "leadership", "internship-like", "creative", "online", "on-campus residential"],
  counselingSupport: ["strong", "moderate", "limited"],
  testSituation: ["no SAT/ACT yet", "SAT taken", "ACT taken", "not planning yet"],
  confidence: ["low", "medium", "high"],
};
