import { StudentProfile } from "@/types";

export const sampleProfile: StudentProfile = {
  dreamMajor: "Computer Science",
  dreamUniversities: ["Stanford", "Carnegie Mellon", "ASU", "Georgia Tech"],
  dreamPrograms: ["Summit AI Research Lab", "Applied AI for Good"],
  academicInterests: ["AI", "machine learning", "software engineering"],
  careerInterests: ["AI engineer", "product builder"],
  gradeLevel: "11",
  gpaRange: "3.6-3.8",
  budgetLevel: "moderate",
  locationPreference: "west coast",
  summerAvailability: "4-6 weeks",
  selectivityComfort: "reach-heavy",
  desiredStyles: ["research", "internship-like", "on-campus residential"],
  coursesAvailable: ["AP Calculus AB", "AP Computer Science A", "AP Physics 1", "Honors English", "Dual Enrollment Statistics"],
  clubsAvailable: ["Robotics Club", "Coding Club", "Math Team", "Student Government", "NHS"],
  leadershipOpportunities: ["Coding Club officer", "Robotics project lead", "Peer tutoring", "Hackathon organizer"],
  localResearchAvailable: true,
  internshipsAvailable: false,
  volunteeringShadowingAvailable: true,
  counselingSupport: "moderate",
  extracurriculars: ["Coding Club", "Math Team", "peer tutoring"],
  leadershipRoles: ["Math Team captain"],
  projectsAwardsCompetitions: ["built a study app", "regional hackathon finalist", "AMC participant"],
  strengths: ["coding foundation", "math", "self-driven projects"],
  weaknesses: ["limited research experience", "wants stronger leadership story", "essay narrative feels scattered"],
  testSituation: "no SAT/ACT yet",
  testingConfidence: "medium",
  personalStatementThemes: ["building tools for students", "curiosity about AI", "balancing ambition with self-doubt"],
  majorExperiences: ["self-taught programming", "helping classmates with math", "first family member aiming for elite STEM schools"],
  essayWritingConfidence: "medium",
};

export const sampleProfiles: Array<{ id: string; label: string; description: string; profile: StudentProfile }> = [
  {
    id: "cs-builder",
    label: "AI / CS Student",
    description: "Research-oriented junior targeting selective CS programs",
    profile: sampleProfile,
  },
  {
    id: "pre-med",
    label: "Pre-Med Student",
    description: "Service-driven student with strong science goals",
    profile: {
      dreamMajor: "Biology",
      dreamUniversities: ["Johns Hopkins", "Duke", "Emory", "Case Western"],
      dreamPrograms: ["BioFuture Medical Scholars", "Health Innovation Research Scholars"],
      academicInterests: ["biology", "public health", "neuroscience"],
      careerInterests: ["physician", "public health researcher"],
      gradeLevel: "11",
      gpaRange: "3.9+",
      budgetLevel: "moderate",
      locationPreference: "east coast",
      summerAvailability: "4-6 weeks",
      selectivityComfort: "balanced",
      desiredStyles: ["research", "academic enrichment", "on-campus residential"],
      coursesAvailable: ["AP Biology", "AP Chemistry", "AP Statistics", "Honors Anatomy", "Dual Enrollment Psychology"],
      clubsAvailable: ["HOSA", "Science Olympiad", "NHS", "Key Club", "Debate"],
      leadershipOpportunities: ["HOSA officer", "hospital volunteer coordinator", "peer health club lead"],
      localResearchAvailable: false,
      internshipsAvailable: false,
      volunteeringShadowingAvailable: true,
      counselingSupport: "strong",
      extracurriculars: ["HOSA", "hospital volunteering", "Science Olympiad"],
      leadershipRoles: ["Key Club secretary"],
      projectsAwardsCompetitions: ["regional HOSA medalist", "organized blood drive"],
      strengths: ["science coursework", "service orientation", "reliability"],
      weaknesses: ["limited lab research", "testing anxiety", "story feels too conventional"],
      testSituation: "SAT taken",
      testingConfidence: "low",
      personalStatementThemes: ["service in healthcare settings", "watching family navigate illness", "learning to stay calm under pressure"],
      majorExperiences: ["weekly hospital volunteering", "supporting an ill grandparent", "health education project at school"],
      essayWritingConfidence: "medium",
    },
  },
  {
    id: "policy-writer",
    label: "Policy / Humanities Student",
    description: "Writing-heavy student focused on policy, leadership, and civic voice",
    profile: {
      dreamMajor: "Public Policy",
      dreamUniversities: ["Georgetown", "Brown", "William & Mary", "George Washington"],
      dreamPrograms: ["Civic Humanities Fellows", "Global Policy Dialogue"],
      academicInterests: ["history", "government", "politics", "writing"],
      careerInterests: ["policy analyst", "law", "journalism"],
      gradeLevel: "10",
      gpaRange: "3.6-3.8",
      budgetLevel: "low",
      locationPreference: "east coast",
      summerAvailability: "2-4 weeks",
      selectivityComfort: "balanced",
      desiredStyles: ["leadership", "research", "academic enrichment"],
      coursesAvailable: ["AP World History", "AP English Language", "Honors Government", "Debate elective", "Dual Enrollment Sociology"],
      clubsAvailable: ["Debate", "Model UN", "Student Government", "School Newspaper", "NHS"],
      leadershipOpportunities: ["student newspaper editor", "Model UN chair", "class representative"],
      localResearchAvailable: false,
      internshipsAvailable: true,
      volunteeringShadowingAvailable: true,
      counselingSupport: "limited",
      extracurriculars: ["Debate", "school newspaper", "community volunteering"],
      leadershipRoles: ["debate captain"],
      projectsAwardsCompetitions: ["state speech finalist", "published op-ed in local paper"],
      strengths: ["writing voice", "public speaking", "initiative"],
      weaknesses: ["less quantitative rigor", "college list realism", "needs a more distinct central theme"],
      testSituation: "not planning yet",
      testingConfidence: "medium",
      personalStatementThemes: ["finding a public voice", "speaking up for others", "navigating identity in community spaces"],
      majorExperiences: ["student newspaper investigations", "debate leadership", "city youth council participation"],
      essayWritingConfidence: "high",
    },
  },
];

export const formOptions = {
  gradeLevels: ["9", "10", "11", "12"],
  gpaRanges: ["3.9+", "3.6-3.8", "3.3-3.5", "3.0-3.2", "below 3.0"],
  budgetLevels: ["low", "moderate", "high", "flexible"],
  locationPreferences: ["west coast", "east coast", "south", "midwest", "online only", "no strong preference"],
  summerAvailability: ["2-4 weeks", "4-6 weeks", "6-8 weeks", "flexible"],
  selectivityComfort: ["reach-heavy", "balanced", "accessible"],
  styles: ["research", "academic enrichment", "leadership", "internship-like", "creative", "online", "on-campus residential"],
  counselingSupport: ["strong", "moderate", "limited"],
  testSituation: ["no SAT/ACT yet", "SAT taken", "ACT taken", "not planning yet"],
  confidence: ["low", "medium", "high"],
};
